-- Полный банк заданий для адаптивного интервью аналитика данных.
-- Активный банк: 9 модулей * 3 уровня сложности * 5 заданий = 135 заданий.
-- Задания самодостаточные: все данные, числа и структуры таблиц, необходимые
-- для ответа, указаны прямо в формулировках.

BEGIN;

INSERT INTO competencies (
    code,
    title,
    group_name,
    description,
    initial_probability
)
VALUES
    ('missing_values', 'Обработка пропущенных значений', 'Подготовка данных', 'Анализ пропусков и выбор корректного способа обработки.', 0.4500),
    ('outliers_duplicates', 'Аномалии и дубликаты', 'Подготовка данных', 'Поиск выбросов, дублей и принятие решений по очистке данных.', 0.4500),
    ('data_transformation', 'Преобразование и нормализация данных', 'Подготовка данных', 'Кодирование, масштабирование и приведение данных к единой структуре.', 0.4500),
    ('sql_databases', 'SQL и работа с базами данных', 'Подготовка данных', 'Выборки, фильтрация, агрегация, группировки и соединения таблиц.', 0.4500),
    ('descriptive_statistics', 'Описательная статистика', 'Анализ данных', 'Меры центра, разброса и первичный анализ распределений.', 0.4500),
    ('hypothesis_testing', 'Проверка статистических гипотез', 'Анализ данных', 'Формулирование гипотез, выбор критерия и интерпретация результата.', 0.4500),
    ('simple_models', 'Простые модели анализа данных', 'Анализ данных', 'Базовые модели регрессии и классификации, метрики качества.', 0.4500),
    ('data_visualization', 'Визуализация данных', 'Интерпретация результатов', 'Выбор графиков, оформление и корректная интерпретация визуализаций.', 0.4500),
    ('business_interpretation', 'Аналитическая интерпретация', 'Интерпретация результатов', 'Интерпретация структурных связей, временных зависимостей и перевод результатов анализа в бизнес-выводы.', 0.4500)
ON CONFLICT (code) DO UPDATE SET
    title = EXCLUDED.title,
    group_name = EXCLUDED.group_name,
    description = EXCLUDED.description,
    initial_probability = EXCLUDED.initial_probability,
    is_active = TRUE;

-- Перед загрузкой финального банка все прежние задания выводятся из активного
-- подбора. После загрузки незадействованные старые задания удаляются.
UPDATE tasks
SET is_active = FALSE;

WITH task_seed AS (
    SELECT *
    FROM jsonb_to_recordset($task_bank$
[
  {"competency_code":"missing_values","title":"MV-E01 - Понятие пропуска","question_text":"Что в аналитике данных обычно называют пропущенным значением?","task_type":"single_choice","difficulty":"easy","options":[{"id":"empty_or_null","label":"Отсутствующее значение в ячейке, например NULL, NA или пустая строка"},{"id":"zero","label":"Любое значение, равное нулю"},{"id":"duplicate","label":"Повторяющаяся строка в таблице"},{"id":"outlier","label":"Слишком большое числовое значение"}],"correct_answer":{"option_id":"empty_or_null"},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-E02 - Доля пропусков","question_text":"Какой показатель первым помогает понять масштаб проблемы пропусков в столбце?","task_type":"single_choice","difficulty":"easy","options":[{"id":"missing_share","label":"Доля пропущенных значений в столбце"},{"id":"max_value","label":"Максимальное значение столбца"},{"id":"row_order","label":"Порядковый номер первой строки"},{"id":"file_size","label":"Размер файла на диске"}],"correct_answer":{"option_id":"missing_share"},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-E03 - Робастное заполнение","question_text":"Чем обычно лучше заполнить пропуски в числовом признаке, если распределение сильно скошено и есть выбросы?","task_type":"single_choice","difficulty":"easy","options":[{"id":"median","label":"Медианой"},{"id":"mean","label":"Средним арифметическим без проверки выбросов"},{"id":"random_text","label":"Случайной текстовой меткой"},{"id":"max","label":"Максимальным значением"}],"correct_answer":{"option_id":"median"},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-E04 - Проверки перед импутацией","question_text":"Какие действия корректно выполнить перед заполнением пропусков? Выберите все подходящие варианты.","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"share","label":"Оценить долю пропусков"},{"id":"pattern","label":"Проверить, связаны ли пропуски с другими признаками"},{"id":"distribution","label":"Изучить распределение признака"},{"id":"always_zero","label":"Всегда заменить пропуски нулями без анализа"}],"correct_answer":{"option_ids":["share","pattern","distribution"]},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-E05 - Тип пропусков и смысл","question_text":"Сопоставьте тип пропусков с кратким описанием.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"mcar","label":"MCAR"},{"id":"mar","label":"MAR"},{"id":"mnar","label":"MNAR"}],"matches":[{"id":"random","label":"Пропуски не связаны ни с наблюдаемыми, ни со скрытыми значениями"},{"id":"observed","label":"Вероятность пропуска объясняется другими наблюдаемыми признаками"},{"id":"hidden","label":"Пропуск связан с самим ненаблюдаемым значением"}]},"correct_answer":{"matches":{"mcar":"random","mar":"observed","mnar":"hidden"}},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-M01 - Небольшая доля пропусков","question_text":"В признаке age пропущено около 4% значений, распределение умеренно скошено, модель требует числовую матрицу без NULL. Какой первый способ обработки наиболее обоснован?","task_type":"single_choice","difficulty":"medium","options":[{"id":"median","label":"Заполнить медианой после проверки распределения"},{"id":"delete_column","label":"Удалить весь столбец age"},{"id":"zero","label":"Заменить все пропуски нулями"},{"id":"target","label":"Заполнить значением целевой переменной"}],"correct_answer":{"option_id":"median"},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-M02 - Пропуски в категории","question_text":"В столбце acquisition_channel пропуски означают, что источник привлечения не был зафиксирован системой. Какие варианты обработки можно рассмотреть?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"unknown","label":"Создать отдельную категорию unknown или not_tracked"},{"id":"mode","label":"Проверить возможность заполнения модой, если это не исказит выводы"},{"id":"indicator","label":"Добавить индикатор наличия пропуска"},{"id":"mean","label":"Заполнить средним арифметическим"}],"correct_answer":{"option_ids":["unknown","mode","indicator"]},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-M03 - Метод и ситуация","question_text":"Сопоставьте ситуацию с наиболее уместным первым решением.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"few_random","label":"1% случайных пропусков в строках"},{"id":"important_category","label":"Пропуски в важной категориальной переменной"},{"id":"time_series_gap","label":"Короткие разрывы во временном ряду"}],"matches":[{"id":"drop_rows","label":"Рассмотреть удаление строк после оценки потерь"},{"id":"unknown_indicator","label":"Добавить категорию unknown и индикатор пропуска"},{"id":"interpolate","label":"Рассмотреть интерполяцию с проверкой сезонности"}]},"correct_answer":{"matches":{"few_random":"drop_rows","important_category":"unknown_indicator","time_series_gap":"interpolate"}},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-M04 - Проверки revenue","question_text":"В таблице заказов есть пропуски в revenue. Опишите, какие проверки нужно выполнить перед выбором способа заполнения и почему простой ноль может исказить анализ.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["указана оценка доли пропусков","проверена связь пропусков с сегментом, датой или каналом","учтено распределение revenue и выбросы","объяснено, почему ноль может означать не отсутствие выручки, а ошибку сбора"]}},
  {"competency_code":"missing_values","title":"MV-M05 - Пропуски перед A/B анализом","question_text":"В A/B тесте у части пользователей отсутствует значение device_type, а конверсия сравнивается по устройствам. Опишите безопасный план обработки таких пропусков перед анализом.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["предложена проверка доли пропусков по группам A и B","описан риск смещения при неравномерных пропусках","предложена отдельная категория или индикатор пропуска","сделан вывод о влиянии обработки на интерпретацию конверсии"]}},
  {"competency_code":"missing_values","title":"MV-H01 - Кейс с региональными пропусками","question_text":"Кейс. В датасете интернет-магазина 50000 заказов. В поле revenue пропущено 18% значений; 70% этих пропусков приходится на регион Far East, где часть платежей проходит через отдельного провайдера. Средняя выручка нужна для отчета по регионам. Опишите, как диагностировать механизм пропусков и какой способ обработки выбрать для отчета.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["распознано, что пропуски не выглядят полностью случайными","предложена проверка по регионам, провайдерам, датам и статусам оплаты","обосновано, почему глобальная средняя может исказить региональный отчет","предложена сегментная импутация, отдельная категория качества данных или исключение с оговоркой","описано влияние выбранного решения на бизнес-вывод"]}},
  {"competency_code":"missing_values","title":"MV-H02 - Кейс с временным рядом","question_text":"Кейс. Есть дневной ряд посещений сайта за 90 дней. В таблице отсутствуют значения за 3 отдельных дня и за один непрерывный период из 8 дней после сбоя трекера. Нужно построить тренд посещаемости. Предложите разные способы обработки коротких и длинных разрывов и критерии выбора.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["разделены короткие и длинные разрывы","для коротких разрывов рассмотрена интерполяция или локальная оценка","для длинного сбоя указана необходимость маркировки или исключения периода из тренда","учтена недельная сезонность","описаны ограничения интерпретации после восстановления данных"]}},
  {"competency_code":"missing_values","title":"MV-H03 - Кейс перед моделью оттока","question_text":"Кейс. Для модели оттока есть признаки tenure, monthly_spend, support_tickets и plan_type. В monthly_spend пропущено 12% значений, причем пропуски чаще у клиентов с новым тарифом. Опишите пайплайн обработки пропусков так, чтобы не получить утечку данных и не исказить оценку качества модели.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["учтена связь пропусков с тарифом","предложено обучать импутер только на train-части","предложен индикатор пропуска","обоснован выбор медианной или групповой импутации","упомянута проверка качества модели и стабильности выводов после обработки"]}},
  {"competency_code":"missing_values","title":"MV-H04 - Риски удаления строк","question_text":"В датасете 30000 клиентов пропуски в income есть у 22% строк и чаще встречаются у молодых клиентов. Какие риски возникнут, если просто удалить все строки с пропусками?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"sample_bias","label":"Может измениться состав выборки и появиться смещение по возрасту"},{"id":"power_loss","label":"Снизится размер выборки и статистическая мощность анализа"},{"id":"target_shift","label":"Может измениться распределение целевой переменной"},{"id":"always_better","label":"Качество анализа гарантированно вырастет, потому что пропусков не останется"}],"correct_answer":{"option_ids":["sample_bias","power_loss","target_shift"]},"rubric":{"criteria":[]}},
  {"competency_code":"missing_values","title":"MV-H05 - Диагностика и действие","question_text":"Сопоставьте результат диагностики пропусков с наиболее корректным действием.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"group_shift","label":"Пропуски сконцентрированы в одном сегменте"},{"id":"random_small","label":"Пропусков мало и они распределены случайно"},{"id":"target_related","label":"Пропуски связаны с целевой переменной"}],"matches":[{"id":"segment_strategy","label":"Использовать сегментную стратегию и явно описать ограничение"},{"id":"simple_strategy","label":"Рассмотреть простое удаление или базовую импутацию после проверки потерь"},{"id":"leakage_check","label":"Проверить риск смещения и утечки, добавить индикатор пропуска"}]},"correct_answer":{"matches":{"group_shift":"segment_strategy","random_small":"simple_strategy","target_related":"leakage_check"}},"rubric":{"criteria":[]}},

  {"competency_code":"outliers_duplicates","title":"OD-E01 - Понятие дубликата","question_text":"Что обычно называют полным дубликатом строки в таблице?","task_type":"single_choice","difficulty":"easy","options":[{"id":"same_all_fields","label":"Строку, у которой совпадают значения всех анализируемых полей"},{"id":"same_one_field","label":"Любую строку с одинаковым значением хотя бы одного поля"},{"id":"missing_row","label":"Строку с пропуском"},{"id":"max_row","label":"Строку с максимальным числовым значением"}],"correct_answer":{"option_id":"same_all_fields"},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-E02 - IQR для выбросов","question_text":"Какой статистический подход часто используют для первичного поиска выбросов в числовом признаке?","task_type":"single_choice","difficulty":"easy","options":[{"id":"iqr","label":"Правило межквартильного размаха IQR"},{"id":"alphabet","label":"Сортировку названий по алфавиту"},{"id":"primary_key","label":"Проверку первичного ключа"},{"id":"join","label":"Соединение таблиц"}],"correct_answer":{"option_id":"iqr"},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-E03 - Не все выбросы ошибки","question_text":"Какое утверждение о выбросах является корректным?","task_type":"single_choice","difficulty":"easy","options":[{"id":"investigate","label":"Выброс нужно исследовать: он может быть ошибкой или реальным редким наблюдением"},{"id":"delete_always","label":"Любой выброс всегда надо удалить"},{"id":"ignore_always","label":"Любой выброс всегда надо игнорировать"},{"id":"fill_mean","label":"Любой выброс надо заменить средним"}],"correct_answer":{"option_id":"investigate"},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-E04 - Признаки проблемы качества","question_text":"Какие признаки могут указывать на проблему качества данных? Выберите все подходящие варианты.","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"duplicate_ids","label":"Одинаковые идентификаторы заказов в строках, где заказ должен быть уникальным"},{"id":"negative_age","label":"Отрицательный возраст клиента"},{"id":"extreme_price","label":"Цена в 100 раз выше типичного диапазона без объяснения"},{"id":"valid_category","label":"Категория товара из утвержденного справочника"}],"correct_answer":{"option_ids":["duplicate_ids","negative_age","extreme_price"]},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-E05 - Проблема и проверка","question_text":"Сопоставьте проблему с первичной проверкой.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"duplicates","label":"Дубли заказов"},{"id":"outliers","label":"Аномально высокие значения"},{"id":"category_typos","label":"Разные написания одной категории"}],"matches":[{"id":"key_check","label":"Проверить бизнес-ключ и число повторов"},{"id":"distribution_check","label":"Посмотреть распределение и квантили"},{"id":"dictionary_check","label":"Сверить со справочником значений"}]},"correct_answer":{"matches":{"duplicates":"key_check","outliers":"distribution_check","category_typos":"dictionary_check"}},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-M01 - Повторы заказов","question_text":"В таблице orders поле order_id должно быть уникальным, но часть order_id встречается дважды с одинаковыми суммами и датами. Какое действие наиболее обосновано первым?","task_type":"single_choice","difficulty":"medium","options":[{"id":"check_rules","label":"Проверить бизнес-ключ, источник дублей и правило дедупликации"},{"id":"sum_all","label":"Сложить все повторяющиеся суммы без проверки"},{"id":"drop_random","label":"Удалить случайную половину таблицы"},{"id":"ignore","label":"Не проверять, потому что дубли не влияют на аналитику"}],"correct_answer":{"option_id":"check_rules"},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-M02 - Выбросы в цене","question_text":"В признаке price большинство значений лежит от 100 до 5000, но есть значения 999999. Какие проверки стоит выполнить?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"source","label":"Проверить источник и формат загрузки цены"},{"id":"currency","label":"Проверить валюту или масштаб единиц измерения"},{"id":"business_case","label":"Проверить, может ли значение быть реальной дорогой покупкой"},{"id":"delete_first","label":"Сразу удалить все большие значения без проверки"}],"correct_answer":{"option_ids":["source","currency","business_case"]},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-M03 - Метод и задача","question_text":"Сопоставьте метод с задачей контроля качества.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"iqr","label":"IQR"},{"id":"zscore","label":"Z-score"},{"id":"dedup_key","label":"Проверка уникального ключа"}],"matches":[{"id":"skewed_numeric","label":"Первичный поиск выбросов в скошенном числовом признаке"},{"id":"standardized_outliers","label":"Поиск экстремальных значений при близком к нормальному распределении"},{"id":"duplicate_orders","label":"Выявление повторов записей заказа"}]},"correct_answer":{"matches":{"iqr":"skewed_numeric","zscore":"standardized_outliers","dedup_key":"duplicate_orders"}},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-M04 - Дедупликация клиентов","question_text":"В CRM один клиент может иметь несколько строк из-за разных email, но одинакового номера телефона. Опишите, как вы построите правило поиска и объединения дублей.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["выделены возможные бизнес-ключи: телефон, email, имя, дата рождения","описана проверка точных и неточных совпадений","предложено не удалять строки без правила приоритета","указана необходимость сохранить трассировку объединения"]}},
  {"competency_code":"outliers_duplicates","title":"OD-M05 - Аномалия или сезонность","question_text":"В дневных продажах один день в 4 раза выше среднего, но это дата крупной распродажи. Объясните, почему автоматическое удаление такого значения может быть ошибкой.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["объяснено отличие ошибки данных от реального редкого события","учтен контекст распродажи или маркетинговой кампании","предложена маркировка события вместо удаления","описано влияние на средние значения и прогноз"]}},
  {"competency_code":"outliers_duplicates","title":"OD-H01 - Кейс с задвоенными заказами","question_text":"Кейс. В таблице заказов 120000 строк. Поле order_id не уникально: 3% заказов повторяются дважды. У части дублей совпадают все поля, у части отличается только updated_at, у части отличается status. Нужно подготовить данные для расчета выручки. Опишите стратегию дедупликации.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["разделены полные и частичные дубли","предложено правило выбора актуальной записи по updated_at или статусу","учтен риск двойного учета выручки","описана проверка после дедупликации","указана необходимость согласовать бизнес-правило статусов"]}},
  {"competency_code":"outliers_duplicates","title":"OD-H02 - Кейс с выбросами зарплат","question_text":"Кейс. В датасете вакансий salary_min и salary_max используются для анализа рынка. Для 2% строк salary_max выше 10000000, а часть значений, вероятно, введена в другой валюте или за год вместо месяца. Опишите, как выявить и обработать эти аномалии.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["предложены проверки валюты, периода и единиц измерения","использованы распределения и квантили по профессии или региону","описаны правила исправления, винзоризации, исключения или маркировки","учтено влияние на медиану и среднее","сформулирована проверка качества после обработки"]}},
  {"competency_code":"outliers_duplicates","title":"OD-H03 - Кейс с выбросами перед моделью","question_text":"Кейс. Для модели оценки стоимости жилья есть признаки area, rooms, price. Несколько квартир имеют area меньше 10, rooms больше 20 или price в 50 раз выше медианы района. Опишите план обработки аномалий перед обучением модели.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["предложены бизнес-правила допустимых диапазонов","учтен контекст района или сегмента жилья","разделены ошибки ввода и реальные редкие объекты","описаны варианты удаления, исправления, лог-преобразования или робастной модели","упомянута проверка влияния на метрики качества"]}},
  {"competency_code":"outliers_duplicates","title":"OD-H04 - Последствия необработанных дублей","question_text":"Какие последствия возможны, если не удалить дубли транзакций перед анализом выручки и конверсии?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"revenue_over","label":"Выручка может быть завышена"},{"id":"conversion_shift","label":"Конверсия может исказиться, если дубли связаны с покупками"},{"id":"model_leak","label":"Модель может переобучиться на повторяющихся наблюдениях"},{"id":"no_effect","label":"Дубли никогда не влияют на расчеты"}],"correct_answer":{"option_ids":["revenue_over","conversion_shift","model_leak"]},"rubric":{"criteria":[]}},
  {"competency_code":"outliers_duplicates","title":"OD-H05 - Решение по аномалии","question_text":"Сопоставьте тип обнаруженной аномалии с корректным решением.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"valid_promo_peak","label":"Реальный пик продаж в день акции"},{"id":"unit_error","label":"Цена записана в копейках вместо рублей"},{"id":"exact_duplicate","label":"Полный дубль строки транзакции"}],"matches":[{"id":"flag_keep","label":"Сохранить значение и добавить признак события"},{"id":"convert_units","label":"Исправить масштаб после подтверждения правила"},{"id":"deduplicate","label":"Оставить одну запись по бизнес-ключу"}]},"correct_answer":{"matches":{"valid_promo_peak":"flag_keep","unit_error":"convert_units","exact_duplicate":"deduplicate"}},"rubric":{"criteria":[]}},

  {"competency_code":"data_transformation","title":"DT-E01 - Нормализация Min-Max","question_text":"Что делает Min-Max нормализация числового признака?","task_type":"single_choice","difficulty":"easy","options":[{"id":"zero_one","label":"Преобразует значения к заданному диапазону, часто от 0 до 1"},{"id":"delete_missing","label":"Удаляет все пропуски"},{"id":"make_text","label":"Преобразует числа в произвольные строки"},{"id":"group_rows","label":"Группирует строки по категориям"}],"correct_answer":{"option_id":"zero_one"},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-E02 - Стандартизация","question_text":"Что обычно означает стандартизация числового признака?","task_type":"single_choice","difficulty":"easy","options":[{"id":"mean_zero_std_one","label":"Преобразование к среднему около 0 и стандартному отклонению около 1"},{"id":"sort_alpha","label":"Сортировку категорий по алфавиту"},{"id":"drop_rows","label":"Удаление строк с выбросами"},{"id":"sql_join","label":"Соединение таблиц"}],"correct_answer":{"option_id":"mean_zero_std_one"},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-E03 - Кодирование категорий","question_text":"Какой метод часто используют для преобразования номинальной категориальной переменной в признаки для модели?","task_type":"single_choice","difficulty":"easy","options":[{"id":"one_hot","label":"One-hot encoding"},{"id":"mean_fill","label":"Заполнение средним"},{"id":"iqr","label":"Межквартильный размах"},{"id":"having","label":"Оператор HAVING"}],"correct_answer":{"option_id":"one_hot"},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-E04 - Типы преобразований","question_text":"Какие действия относятся к преобразованию данных перед анализом? Выберите все подходящие варианты.","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"type_cast","label":"Приведение даты из строки к типу date"},{"id":"scaling","label":"Масштабирование числового признака"},{"id":"encoding","label":"Кодирование категориального признака"},{"id":"random_delete","label":"Случайное удаление половины данных без причины"}],"correct_answer":{"option_ids":["type_cast","scaling","encoding"]},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-E05 - Преобразование и цель","question_text":"Сопоставьте преобразование с основной целью.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"one_hot","label":"One-hot encoding"},{"id":"standard_scaler","label":"StandardScaler"},{"id":"date_parse","label":"Парсинг даты"}],"matches":[{"id":"category_to_binary","label":"Преобразовать номинальную категорию в бинарные признаки"},{"id":"scale_numeric","label":"Привести числовой признак к сопоставимому масштабу"},{"id":"time_features","label":"Получить дату и производные временные признаки"}]},"correct_answer":{"matches":{"one_hot":"category_to_binary","standard_scaler":"scale_numeric","date_parse":"time_features"}},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-M01 - Масштабирование для KNN","question_text":"Вы строите KNN-модель по признакам age и annual_income. Доход измеряется в сотнях тысяч, возраст в десятках. Какое действие наиболее важно перед обучением?","task_type":"single_choice","difficulty":"medium","options":[{"id":"scale","label":"Масштабировать числовые признаки"},{"id":"drop_income","label":"Удалить доход, потому что он большой"},{"id":"sort","label":"Отсортировать строки по возрасту"},{"id":"rename","label":"Переименовать столбцы"}],"correct_answer":{"option_id":"scale"},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-M02 - Порядковая категория","question_text":"Переменная education_level имеет порядок: school, bachelor, master, phd. Какие способы кодирования можно рассмотреть?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"ordinal","label":"Порядковое кодирование с сохранением смысла уровней"},{"id":"one_hot","label":"One-hot encoding, если модель не должна считать расстояния между уровнями линейными"},{"id":"target_check","label":"Проверить влияние выбранного кодирования на модель и интерпретацию"},{"id":"random_numbers","label":"Назначить случайные числа каждому уровню"}],"correct_answer":{"option_ids":["ordinal","one_hot","target_check"]},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-M03 - Проблема и преобразование","question_text":"Сопоставьте проблему с подходящим преобразованием.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"date_string","label":"Дата хранится как строка 2026-05-01"},{"id":"high_cardinality","label":"Категория имеет тысячи уникальных значений"},{"id":"skewed_amount","label":"Сумма покупки сильно скошена вправо"}],"matches":[{"id":"parse_date","label":"Преобразовать к date и извлечь месяц или день недели"},{"id":"rare_grouping","label":"Сгруппировать редкие категории или выбрать устойчивое кодирование"},{"id":"log_transform","label":"Рассмотреть лог-преобразование после проверки нулей"}]},"correct_answer":{"matches":{"date_string":"parse_date","high_cardinality":"rare_grouping","skewed_amount":"log_transform"}},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-M04 - Приведение типов в продажах","question_text":"В выгрузке продаж столбец order_date хранится как текст, amount содержит строки с пробелами и символом рубля, а segment содержит разные регистры. Опишите план преобразования этих полей перед анализом.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["указано преобразование order_date к типу даты","описана очистка amount и преобразование к числу","описана нормализация регистра и пробелов в segment","упомянута проверка ошибок преобразования и пропусков после кастинга"]}},
  {"competency_code":"data_transformation","title":"DT-M05 - Подготовка признаков для регрессии","question_text":"Есть признаки city, room_count, area и price. Опишите, какие преобразования нужны, чтобы построить простую регрессионную модель цены жилья.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["категориальный city преобразован в числовые признаки","числовые признаки проверены на масштаб и выбросы","упомянута обработка пропусков до обучения","описано разделение признаков и целевой переменной"]}},
  {"competency_code":"data_transformation","title":"DT-H01 - Кейс с утечкой при масштабировании","question_text":"Кейс. Датасет клиентов делят на train и test для модели оттока. Аналитик сначала стандартизировал все числовые признаки на всей таблице, а потом сделал разбиение. Объясните, в чем риск такого подхода и как правильно построить пайплайн.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["распознан риск утечки информации из test в параметры масштабирования","описано разбиение train/test до fit преобразователей","указано fit только на train и transform на train/test","упомянут pipeline для воспроизводимости","объяснено влияние на оценку качества модели"]}},
  {"competency_code":"data_transformation","title":"DT-H02 - Кейс с категориальными признаками","question_text":"Кейс. В таблице 200000 заказов есть признаки channel, city, product_category и целевая переменная repeat_purchase. У city 900 уникальных значений, у channel 5. Нужно подготовить признаки для логистической регрессии. Опишите стратегию кодирования и проверки качества.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["разделены низкая и высокая кардинальность категорий","для channel предложен one-hot encoding","для city предложено группирование редких городов или устойчивое кодирование","учтен риск переобучения и утечки при target encoding","описана проверка на validation/test"]}},
  {"competency_code":"data_transformation","title":"DT-H03 - Кейс с временными признаками","question_text":"Кейс. Для прогноза количества заказов есть поля order_timestamp, region, amount. Нужно построить признаки без доступа к будущему. Какие временные признаки можно извлечь и какие ограничения важно соблюсти?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["предложены признаки день недели, месяц, час, праздник или сезон","учтен запрет использовать будущие агрегаты","описаны лаговые или скользящие признаки только из прошлого","упомянута проверка временного разбиения train/test","объяснена связь признаков с бизнес-сезонностью"]}},
  {"competency_code":"data_transformation","title":"DT-H04 - Выбор преобразований для модели","question_text":"Для модели на основе расстояний используются признаки income, age, city и last_login_date. Какие преобразования наиболее уместны?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"scale_numeric","label":"Масштабировать income и age"},{"id":"encode_city","label":"Закодировать city с учетом числа уникальных значений"},{"id":"date_features","label":"Извлечь из last_login_date осмысленные временные признаки"},{"id":"leave_text_date","label":"Оставить дату как произвольную строку, модель сама поймет"}],"correct_answer":{"option_ids":["scale_numeric","encode_city","date_features"]},"rubric":{"criteria":[]}},
  {"competency_code":"data_transformation","title":"DT-H05 - Ошибка преобразования и последствие","question_text":"Сопоставьте ошибку преобразования с возможным последствием.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"fit_all_data","label":"Scaler обучен на всей таблице до train/test split"},{"id":"random_ordinal","label":"Номинальным городам присвоены числа 1, 2, 3 без смысла порядка"},{"id":"unparsed_date","label":"Дата оставлена строкой разного формата"}],"matches":[{"id":"leakage","label":"Утечка информации и завышенная оценка качества"},{"id":"fake_order","label":"Модель может увидеть ложный порядок или расстояние"},{"id":"parse_errors","label":"Ошибки группировки, фильтрации и извлечения периода"}]},"correct_answer":{"matches":{"fit_all_data":"leakage","random_ordinal":"fake_order","unparsed_date":"parse_errors"}},"rubric":{"criteria":[]}},

  {"competency_code":"sql_databases","title":"SQL-E01 - Фильтрация строк","question_text":"Какой оператор SQL используется для фильтрации строк до группировки?","task_type":"single_choice","difficulty":"easy","options":[{"id":"where","label":"WHERE"},{"id":"having","label":"HAVING"},{"id":"order_by","label":"ORDER BY"},{"id":"limit","label":"LIMIT"}],"correct_answer":{"option_id":"where"},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-E02 - Фильтрация групп","question_text":"Какой оператор SQL используется для фильтрации результата после GROUP BY?","task_type":"single_choice","difficulty":"easy","options":[{"id":"having","label":"HAVING"},{"id":"where","label":"WHERE"},{"id":"select","label":"SELECT"},{"id":"join","label":"JOIN"}],"correct_answer":{"option_id":"having"},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-E03 - Агрегация суммы","question_text":"Какая агрегатная функция SQL считает сумму значений в столбце amount?","task_type":"single_choice","difficulty":"easy","options":[{"id":"sum","label":"SUM(amount)"},{"id":"count","label":"COUNT(amount)"},{"id":"avg","label":"AVG(amount)"},{"id":"max","label":"MAX(amount)"}],"correct_answer":{"option_id":"sum"},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-E04 - Базовые части запроса","question_text":"Какие части SQL-запроса обычно нужны, чтобы посчитать выручку по пользователям из таблицы orders?","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"select_user","label":"SELECT user_id"},{"id":"sum_amount","label":"SUM(amount)"},{"id":"group_user","label":"GROUP BY user_id"},{"id":"drop_table","label":"DROP TABLE orders"}],"correct_answer":{"option_ids":["select_user","sum_amount","group_user"]},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-E05 - Оператор и назначение","question_text":"Сопоставьте SQL-оператор с назначением.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"join","label":"JOIN"},{"id":"group_by","label":"GROUP BY"},{"id":"order_by","label":"ORDER BY"}],"matches":[{"id":"combine","label":"Соединяет строки из таблиц по условию"},{"id":"aggregate_groups","label":"Формирует группы для агрегатов"},{"id":"sort_result","label":"Сортирует результат"}]},"correct_answer":{"matches":{"join":"combine","group_by":"aggregate_groups","order_by":"sort_result"}},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-M01 - Выручка за период","question_text":"Есть таблица orders(user_id, order_date, amount). Какой запрос считает выручку каждого пользователя за май 2026 года?","task_type":"single_choice","difficulty":"medium","options":[{"id":"correct","label":"SELECT user_id, SUM(amount) FROM orders WHERE order_date >= '2026-05-01' AND order_date < '2026-06-01' GROUP BY user_id"},{"id":"no_group","label":"SELECT user_id, SUM(amount) FROM orders WHERE order_date >= '2026-05-01'"},{"id":"bad_having","label":"SELECT user_id, amount FROM orders HAVING order_date = '2026-05-01'"},{"id":"count_only","label":"SELECT user_id, COUNT(*) FROM orders"}],"correct_answer":{"option_id":"correct"},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-M02 - Join клиентов и заказов","question_text":"Есть customers(id, segment) и orders(id, customer_id, amount). Какие элементы нужны, чтобы посчитать выручку по segment?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"join","label":"JOIN customers ON customers.id = orders.customer_id"},{"id":"group_segment","label":"GROUP BY customers.segment"},{"id":"sum_amount","label":"SUM(orders.amount)"},{"id":"group_order_id","label":"GROUP BY orders.id как единственная группировка"}],"correct_answer":{"option_ids":["join","group_segment","sum_amount"]},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-M03 - Запрос и задача","question_text":"Сопоставьте задачу с SQL-конструкцией.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"top_users","label":"Найти пользователей с выручкой больше 10000 после агрегации"},{"id":"missing_orders","label":"Показать клиентов без заказов"},{"id":"monthly_revenue","label":"Посчитать выручку по месяцам"}],"matches":[{"id":"having_sum","label":"GROUP BY user_id и HAVING SUM(amount) > 10000"},{"id":"left_join_null","label":"LEFT JOIN и проверка NULL в таблице заказов"},{"id":"date_trunc_group","label":"Группировка по месяцу даты заказа"}]},"correct_answer":{"matches":{"top_users":"having_sum","missing_orders":"left_join_null","monthly_revenue":"date_trunc_group"}},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-M04 - Запрос на средний чек","question_text":"Есть orders(order_id, user_id, order_date, amount). Напишите SQL-запрос, который вернет средний чек по дням за последние 30 дней, если текущая дата считается 2026-06-18.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["использован SELECT по дате заказа или приведению order_date к дню","использован AVG(amount)","есть фильтр по периоду последних 30 дней относительно 2026-06-18","есть GROUP BY по дню","результат отсортирован или пригоден для анализа динамики"]}},
  {"competency_code":"sql_databases","title":"SQL-M05 - Дубликаты заказов SQL","question_text":"В таблице orders(order_id, user_id, amount) нужно найти order_id, которые встречаются больше одного раза. Напишите запрос или опишите его логику.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["используется GROUP BY order_id","используется COUNT(*)","используется HAVING COUNT(*) > 1","ответ показывает понимание поиска дублей по ключу"]}},
  {"competency_code":"sql_databases","title":"SQL-H01 - Кейс с когортной выручкой","question_text":"Кейс. Есть users(user_id, signup_date) и orders(order_id, user_id, order_date, amount). Нужно посчитать выручку за первые 30 дней после регистрации для каждой месячной когорты signup_date. Опишите SQL-логику запроса.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["соединены users и orders по user_id","когорта строится по месяцу signup_date","заказы фильтруются в интервале от signup_date до signup_date плюс 30 дней","используется SUM(amount) и GROUP BY по когорте","учтен LEFT JOIN или интерпретация пользователей без заказов"]}},
  {"competency_code":"sql_databases","title":"SQL-H02 - Кейс с окном повторной покупки","question_text":"Кейс. В orders(user_id, order_date, amount) нужно для каждого заказа найти дату предыдущего заказа пользователя и число дней между заказами. Опишите, какую оконную функцию использовать и как построить запрос.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["используется LAG(order_date)","окно разделено по user_id","задан ORDER BY order_date внутри окна","описан расчет разницы дат","учтено, что у первого заказа предыдущей даты нет"]}},
  {"competency_code":"sql_databases","title":"SQL-H03 - Кейс с качеством join","question_text":"Кейс. После JOIN таблиц orders и payments сумма выручки выросла в 2 раза. В payments у одного заказа может быть несколько платежных событий. Опишите, как диагностировать проблему и переписать запрос, чтобы не получить размножение строк.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["распознана проблема many-to-one или one-to-many join","предложена проверка количества строк до и после JOIN","предложена предварительная агрегация payments до уровня order_id","описано соединение агрегированной таблицы с orders","учтен контроль итоговой суммы после исправления"]}},
  {"competency_code":"sql_databases","title":"SQL-H04 - Выбор конструкций для сложного отчета","question_text":"Нужно построить отчет: выручка по месяцам, доля каждого канала в месячной выручке, топ-3 канала в каждом месяце. Какие SQL-инструменты вероятнее всего понадобятся?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"group_month_channel","label":"GROUP BY по месяцу и каналу"},{"id":"window_sum","label":"Оконная SUM по месяцу для расчета доли"},{"id":"rank","label":"RANK или ROW_NUMBER для топ-3 внутри месяца"},{"id":"drop","label":"DROP TABLE перед расчетом"}],"correct_answer":{"option_ids":["group_month_channel","window_sum","rank"]},"rubric":{"criteria":[]}},
  {"competency_code":"sql_databases","title":"SQL-H05 - Ошибка SQL и исправление","question_text":"Сопоставьте ошибку в SQL-отчете с корректным исправлением.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"where_agg","label":"Фильтр SUM(amount) > 10000 записан в WHERE"},{"id":"join_multiply","label":"JOIN размножает строки заказов"},{"id":"missing_group","label":"В SELECT есть segment и SUM(amount), но нет GROUP BY segment"}],"matches":[{"id":"use_having","label":"Перенести условие на агрегат в HAVING"},{"id":"pre_aggregate","label":"Сначала агрегировать детальную таблицу до нужного ключа"},{"id":"add_group","label":"Добавить группировку по неагрегированному полю"}]},"correct_answer":{"matches":{"where_agg":"use_having","join_multiply":"pre_aggregate","missing_group":"add_group"}},"rubric":{"criteria":[]}},

  {"competency_code":"descriptive_statistics","title":"DS-E01 - Среднее значение","question_text":"Что показывает среднее арифметическое числового признака?","task_type":"single_choice","difficulty":"easy","options":[{"id":"mean","label":"Сумму значений, деленную на их количество"},{"id":"middle_sorted","label":"Средний элемент в отсортированном ряду"},{"id":"max_min","label":"Разницу между максимумом и минимумом"},{"id":"category_count","label":"Количество уникальных категорий"}],"correct_answer":{"option_id":"mean"},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-E02 - Медиана","question_text":"Какая мера центральной тенденции обычно устойчивее к сильным выбросам?","task_type":"single_choice","difficulty":"easy","options":[{"id":"median","label":"Медиана"},{"id":"mean","label":"Среднее арифметическое"},{"id":"max","label":"Максимум"},{"id":"range","label":"Размах"}],"correct_answer":{"option_id":"median"},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-E03 - Стандартное отклонение","question_text":"Что в первую очередь характеризует стандартное отклонение?","task_type":"single_choice","difficulty":"easy","options":[{"id":"spread","label":"Разброс значений вокруг среднего"},{"id":"center","label":"Только центральное значение"},{"id":"row_count","label":"Количество строк таблицы"},{"id":"join_quality","label":"Качество соединения таблиц"}],"correct_answer":{"option_id":"spread"},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-E04 - Описательные показатели","question_text":"Какие показатели относятся к описательной статистике числового признака?","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"mean","label":"Среднее"},{"id":"median","label":"Медиана"},{"id":"std","label":"Стандартное отклонение"},{"id":"primary_key","label":"Первичный ключ таблицы"}],"correct_answer":{"option_ids":["mean","median","std"]},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-E05 - Показатель и смысл","question_text":"Сопоставьте показатель с его смыслом.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"median","label":"Медиана"},{"id":"iqr","label":"IQR"},{"id":"mode","label":"Мода"}],"matches":[{"id":"middle","label":"Центр отсортированного распределения"},{"id":"middle_spread","label":"Разброс между первым и третьим квартилем"},{"id":"most_frequent","label":"Наиболее частое значение"}]},"correct_answer":{"matches":{"median":"middle","iqr":"middle_spread","mode":"most_frequent"}},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-M01 - Среднее или медиана","question_text":"В выборке доходов есть несколько очень больших значений. Какой показатель лучше использовать для типичного дохода?","task_type":"single_choice","difficulty":"medium","options":[{"id":"median","label":"Медиану, потому что она устойчивее к выбросам"},{"id":"mean_only","label":"Только среднее, потому что оно всегда лучше"},{"id":"max","label":"Максимум"},{"id":"count_nulls","label":"Количество пропусков"}],"correct_answer":{"option_id":"median"},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-M02 - Распределение признака","question_text":"Вы изучаете распределение времени доставки. Какие действия помогут описать его корректно?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"hist","label":"Построить гистограмму или оценить форму распределения"},{"id":"center","label":"Посчитать медиану и среднее"},{"id":"spread","label":"Посчитать IQR или стандартное отклонение"},{"id":"ignore_outliers","label":"Не смотреть на выбросы, потому что они не влияют на описание"}],"correct_answer":{"option_ids":["hist","center","spread"]},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-M03 - Ситуация и показатель","question_text":"Сопоставьте аналитическую ситуацию с подходящим описательным показателем.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"skewed_income","label":"Типичный доход при сильной асимметрии"},{"id":"stable_process","label":"Разброс времени обработки заявок"},{"id":"popular_category","label":"Самый частый тариф"}],"matches":[{"id":"median","label":"Медиана"},{"id":"std_or_iqr","label":"Стандартное отклонение или IQR"},{"id":"mode","label":"Мода"}]},"correct_answer":{"matches":{"skewed_income":"median","stable_process":"std_or_iqr","popular_category":"mode"}},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-M04 - Описание продаж","question_text":"Есть 1000 заказов со столбцом amount. Опишите набор описательных статистик, который вы рассчитаете, чтобы понять типичный чек и разброс заказов.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["названы среднее и медиана","названы показатели разброса: стандартное отклонение, IQR или квантили","упомянута проверка выбросов и асимметрии","объяснено, как показатели помогают интерпретировать типичный чек"]}},
  {"competency_code":"descriptive_statistics","title":"DS-M05 - Сравнение сегментов","question_text":"Два клиентских сегмента имеют одинаковое среднее значение чека, но разное стандартное отклонение. Объясните, какой вывод можно сделать о поведении сегментов.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["объяснено, что одинаковое среднее не означает одинаковое распределение","интерпретирован больший разброс как менее однородное поведение","упомянута необходимость смотреть медиану, квантили или график","сделана связь с бизнес-решением или сегментацией"]}},
  {"competency_code":"descriptive_statistics","title":"DS-H01 - Кейс с описанием чеков","question_text":"Кейс. В интернет-магазине чеки за неделю: 350, 410, 390, 430, 450, 470, 12000. Нужно дать руководителю оценку типичного чека. Какие показатели рассчитать и как объяснить влияние значения 12000?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["рассчитан или качественно выбран центр: медиана предпочтительнее среднего","объяснено влияние выброса 12000 на среднее","предложены квантили или IQR","указано, что 12000 нужно проверить как ошибку или крупный заказ","сформулирован понятный бизнес-вывод"]}},
  {"competency_code":"descriptive_statistics","title":"DS-H02 - Кейс с распределением времени доставки","question_text":"Кейс. Время доставки по 5000 заказам имеет длинный правый хвост: большинство доставок до 2 дней, но 5% заказов идут дольше недели. Нужно подготовить описание для операционной команды. Какие статистики и графики использовать?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["предложены медиана, квантили и доля заказов выше порога","объяснено ограничение среднего при правом хвосте","предложены гистограмма или boxplot","выделены операционные метрики SLA","сформулированы выводы для контроля задержек"]}},
  {"competency_code":"descriptive_statistics","title":"DS-H03 - Кейс с групповой статистикой","question_text":"Кейс. У трех регионов одинаковая средняя выручка на клиента, но в одном регионе IQR в 3 раза выше, а медиана ниже среднего. Как интерпретировать такую картину и какие дополнительные проверки провести?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["распознана неоднородность и правосторонняя асимметрия","объяснено различие среднего, медианы и IQR","предложена проверка выбросов или крупных клиентов","предложено смотреть распределения по регионам","сделан осторожный вывод для сравнения регионов"]}},
  {"competency_code":"descriptive_statistics","title":"DS-H04 - Описание скошенного распределения","question_text":"Какие показатели наиболее уместны для описания сильно скошенного распределения суммы заказа?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"median","label":"Медиана"},{"id":"iqr","label":"IQR или квантили"},{"id":"p95","label":"95-й процентиль"},{"id":"mean_only","label":"Только среднее без дополнительных показателей"}],"correct_answer":{"option_ids":["median","iqr","p95"]},"rubric":{"criteria":[]}},
  {"competency_code":"descriptive_statistics","title":"DS-H05 - Паттерн распределения и вывод","question_text":"Сопоставьте наблюдение в распределении с корректной интерпретацией.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"mean_gt_median","label":"Среднее заметно больше медианы"},{"id":"large_iqr","label":"Большой IQR внутри сегмента"},{"id":"many_zeros","label":"Большая доля нулевых значений"}],"matches":[{"id":"right_skew","label":"Вероятна правая асимметрия или крупные значения"},{"id":"heterogeneous","label":"Сегмент неоднороден по анализируемому признаку"},{"id":"zero_process","label":"Нужна отдельная интерпретация отсутствия события или покупок"}]},"correct_answer":{"matches":{"mean_gt_median":"right_skew","large_iqr":"heterogeneous","many_zeros":"zero_process"}},"rubric":{"criteria":[]}},

  {"competency_code":"hypothesis_testing","title":"HT-E01 - Нулевая гипотеза","question_text":"Что такое нулевая гипотеза в статистической проверке?","task_type":"single_choice","difficulty":"easy","options":[{"id":"no_effect","label":"Базовое предположение об отсутствии эффекта или различия"},{"id":"best_result","label":"Предположение, которое аналитик хочет обязательно доказать"},{"id":"sample_size","label":"Размер выборки"},{"id":"chart_type","label":"Тип графика"}],"correct_answer":{"option_id":"no_effect"},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-E02 - p-value","question_text":"Как лучше интерпретировать p-value в классической проверке гипотез?","task_type":"single_choice","difficulty":"easy","options":[{"id":"prob_data_or_more_extreme","label":"Вероятность получить такие или более экстремальные данные при верной нулевой гипотезе"},{"id":"prob_h0_true","label":"Вероятность того, что нулевая гипотеза истинна"},{"id":"effect_size","label":"Размер эффекта в бизнес-единицах"},{"id":"sample_count","label":"Количество наблюдений"}],"correct_answer":{"option_id":"prob_data_or_more_extreme"},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-E03 - Уровень значимости","question_text":"Что обычно обозначает уровень значимости alpha = 0.05?","task_type":"single_choice","difficulty":"easy","options":[{"id":"type1_threshold","label":"Порог допустимой вероятности ошибки первого рода"},{"id":"accuracy","label":"Точность модели 95%"},{"id":"conversion","label":"Конверсию 5%"},{"id":"missing_share","label":"Долю пропусков 5%"}],"correct_answer":{"option_id":"type1_threshold"},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-E04 - Перед A/B тестом","question_text":"Что нужно определить до запуска A/B теста? Выберите все подходящие варианты.","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"metric","label":"Основную метрику"},{"id":"hypotheses","label":"Нулевую и альтернативную гипотезы"},{"id":"sample_size","label":"Оценку требуемого размера выборки"},{"id":"peek","label":"Правило останавливать тест при первом удачном дне"}],"correct_answer":{"option_ids":["metric","hypotheses","sample_size"]},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-E05 - Критерий и данные","question_text":"Сопоставьте тип задачи с подходящим направлением проверки.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"two_means","label":"Сравнить средний чек двух независимых групп"},{"id":"two_props","label":"Сравнить конверсию двух версий страницы"},{"id":"association","label":"Проверить связь двух числовых переменных"}],"matches":[{"id":"t_test","label":"Тест для сравнения средних при выполнении предпосылок"},{"id":"prop_test","label":"Тест для сравнения долей"},{"id":"correlation","label":"Корреляционный анализ"}]},"correct_answer":{"matches":{"two_means":"t_test","two_props":"prop_test","association":"correlation"}},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-M01 - Выбор критерия для конверсии","question_text":"В A/B тесте сравнивают конверсию: покупка была или не была. Какой тип проверки наиболее уместен?","task_type":"single_choice","difficulty":"medium","options":[{"id":"two_proportions","label":"Проверка различий долей между двумя группами"},{"id":"mean_height","label":"Сравнение среднего роста"},{"id":"deduplicate","label":"Поиск дублей"},{"id":"minmax","label":"Min-Max нормализация"}],"correct_answer":{"option_id":"two_proportions"},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-M02 - Интерпретация результата","question_text":"A/B тест дал p-value = 0.03 при alpha = 0.05. Какие утверждения корректны?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"reject","label":"Есть основание отвергнуть нулевую гипотезу на уровне 0.05"},{"id":"not_prob_h0","label":"Это не означает, что вероятность истинности H0 равна 3%"},{"id":"need_effect","label":"Нужно оценить размер эффекта и практическую значимость"},{"id":"guarantee_profit","label":"Это гарантирует рост прибыли"}],"correct_answer":{"option_ids":["reject","not_prob_h0","need_effect"]},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-M03 - Ошибка и пример","question_text":"Сопоставьте понятие с примером в A/B тесте.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"type1","label":"Ошибка первого рода"},{"id":"type2","label":"Ошибка второго рода"},{"id":"power","label":"Статистическая мощность"}],"matches":[{"id":"false_positive","label":"Решили, что эффект есть, хотя его нет"},{"id":"false_negative","label":"Не обнаружили существующий эффект"},{"id":"detect_true","label":"Вероятность обнаружить эффект заданного размера"}]},"correct_answer":{"matches":{"type1":"false_positive","type2":"false_negative","power":"detect_true"}},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-M04 - Проверка нового дизайна","question_text":"Компания изменила дизайн страницы. Опишите шаги проверки, повлиял ли дизайн на конверсию в покупку.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["сформулированы H0 и H1","зафиксирована метрика конверсии","описаны группы A и B и рандомизация","указан критерий для сравнения долей или доверительный интервал","результат интерпретируется с учетом размера эффекта"]}},
  {"competency_code":"hypothesis_testing","title":"HT-M05 - Корреляция не описательная статистика","question_text":"Аналитик хочет проверить, связаны ли рекламные расходы и число заявок по дням. Опишите, почему это задача проверки связи переменных, а не просто расчет описательных статистик.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["объяснено, что проверяется связь между переменными","упомянут коэффициент корреляции или регрессионный подход","описана необходимость статистической проверки значимости связи","отмечено, что описательная статистика только суммирует отдельные распределения"]}},
  {"competency_code":"hypothesis_testing","title":"HT-H01 - Кейс с A/B тестом конверсии","question_text":"Кейс. В группе A было 10000 пользователей и 620 покупок, в группе B 9800 пользователей и 690 покупок. Нужно решить, улучшила ли новая страница конверсию. Опишите гипотезы, критерий, интерпретацию статистической и практической значимости.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["сформулированы H0 об отсутствии различия долей и H1 о различии или росте","выбран тест для сравнения долей или доверительный интервал","посчитана или качественно оценена конверсия в обеих группах","разделены статистическая и практическая значимость","учтены условия рандомизации и достаточности данных"]}},
  {"competency_code":"hypothesis_testing","title":"HT-H02 - Кейс с множественными проверками","question_text":"Кейс. После эксперимента аналитик проверил 25 метрик и нашел 2 значимых результата при alpha = 0.05. Объясните, почему это рискованно, и как корректнее организовать анализ.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["распознан риск множественных сравнений и ложноположительных выводов","предложено заранее определить основную метрику","упомянуты корректировки или контроль FDR при множественных проверках","разделены primary и secondary метрики","сформулирован осторожный вывод по найденным эффектам"]}},
  {"competency_code":"hypothesis_testing","title":"HT-H03 - Кейс с выбором критерия","question_text":"Кейс. Нужно сравнить время доставки до и после изменения логистики для одних и тех же складов по 30 дням до и 30 дням после. Распределение различий скошено, есть выбросы. Опишите выбор статистического подхода и проверки предпосылок.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["распознана зависимость или парность наблюдений, если сравнение идет по тем же складам","предложена проверка распределения различий и выбросов","рассмотрен парный t-test при выполнении предпосылок или непараметрическая альтернатива","учтен размер эффекта и доверительный интервал","описана бизнес-интерпретация изменения времени доставки"]}},
  {"competency_code":"hypothesis_testing","title":"HT-H04 - Что проверить перед выводом","question_text":"Перед выводом об эффекте A/B теста какие проверки особенно важны?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"randomization","label":"Баланс и корректность рандомизации групп"},{"id":"sample_size","label":"Достаточность размера выборки или мощности"},{"id":"peeking","label":"Наличие преждевременных остановок и многократных просмотров результата"},{"id":"color","label":"Цвет графика как главный статистический критерий"}],"correct_answer":{"option_ids":["randomization","sample_size","peeking"]},"rubric":{"criteria":[]}},
  {"competency_code":"hypothesis_testing","title":"HT-H05 - Результат и корректный вывод","question_text":"Сопоставьте результат анализа с корректной интерпретацией.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"p_small_effect_tiny","label":"p-value маленький, эффект очень мал"},{"id":"p_large_low_power","label":"p-value большой, выборка мала"},{"id":"ci_cross_zero","label":"Доверительный интервал эффекта включает ноль"}],"matches":[{"id":"practical_check","label":"Нужно проверить практическую значимость, а не только статистическую"},{"id":"inconclusive","label":"Нельзя уверенно говорить об отсутствии эффекта без анализа мощности"},{"id":"not_significant","label":"На выбранном уровне нет убедительного доказательства отличия"}]},"correct_answer":{"matches":{"p_small_effect_tiny":"practical_check","p_large_low_power":"inconclusive","ci_cross_zero":"not_significant"}},"rubric":{"criteria":[]}},

  {"competency_code":"simple_models","title":"SM-E01 - Линейная регрессия","question_text":"Для какой задачи чаще всего используют линейную регрессию?","task_type":"single_choice","difficulty":"easy","options":[{"id":"numeric_target","label":"Прогноз числовой целевой переменной"},{"id":"deduplicate","label":"Удаление дублей"},{"id":"chart_select","label":"Выбор типа диаграммы"},{"id":"sql_filter","label":"Фильтрация строк в SQL"}],"correct_answer":{"option_id":"numeric_target"},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-E02 - Логистическая регрессия","question_text":"Для какой задачи обычно применяют логистическую регрессию?","task_type":"single_choice","difficulty":"easy","options":[{"id":"binary_classification","label":"Бинарная классификация"},{"id":"sum_revenue","label":"Суммирование выручки"},{"id":"parse_date","label":"Преобразование даты"},{"id":"boxplot","label":"Построение boxplot"}],"correct_answer":{"option_id":"binary_classification"},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-E03 - Accuracy","question_text":"Что показывает accuracy в задаче классификации?","task_type":"single_choice","difficulty":"easy","options":[{"id":"correct_share","label":"Долю правильно классифицированных объектов"},{"id":"false_positive_only","label":"Только долю ложноположительных ошибок"},{"id":"mean_error","label":"Среднюю абсолютную ошибку регрессии"},{"id":"data_size","label":"Размер датасета"}],"correct_answer":{"option_id":"correct_share"},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-E04 - Метрики классификации","question_text":"Какие метрики относятся к оценке классификации? Выберите все подходящие варианты.","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"precision","label":"Precision"},{"id":"recall","label":"Recall"},{"id":"f1","label":"F1-score"},{"id":"sum","label":"SUM(amount)"}],"correct_answer":{"option_ids":["precision","recall","f1"]},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-E05 - Модель и задача","question_text":"Сопоставьте модель или метод с типовой задачей.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"linear_regression","label":"Линейная регрессия"},{"id":"logistic_regression","label":"Логистическая регрессия"},{"id":"kmeans","label":"K-means"}],"matches":[{"id":"predict_number","label":"Прогнозировать числовое значение"},{"id":"predict_class","label":"Оценить вероятность класса"},{"id":"cluster","label":"Сгруппировать похожие объекты без целевой переменной"}]},"correct_answer":{"matches":{"linear_regression":"predict_number","logistic_regression":"predict_class","kmeans":"cluster"}},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-M01 - Метрика при дисбалансе","question_text":"В задаче выявления мошенничества положительный класс составляет 2%. Какая проблема есть у одной только accuracy?","task_type":"single_choice","difficulty":"medium","options":[{"id":"misleading","label":"Она может быть высокой даже у модели, которая почти всегда предсказывает отрицательный класс"},{"id":"always_best","label":"Она всегда лучшая метрика при дисбалансе"},{"id":"no_labels","label":"Она не требует истинных меток"},{"id":"sql_only","label":"Она применима только в SQL"}],"correct_answer":{"option_id":"misleading"},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-M02 - Выбор метрик","question_text":"Для классификации заявок на риск дефолта какие метрики стоит смотреть вместе с accuracy?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"precision","label":"Precision"},{"id":"recall","label":"Recall"},{"id":"roc_auc","label":"ROC AUC"},{"id":"month_name","label":"Название месяца"}],"correct_answer":{"option_ids":["precision","recall","roc_auc"]},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-M03 - Метрика и бизнес-ошибка","question_text":"Сопоставьте метрику с ситуацией, где она особенно важна.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"precision","label":"Precision"},{"id":"recall","label":"Recall"},{"id":"mae","label":"MAE"}],"matches":[{"id":"false_positive_cost","label":"Дороги ложные срабатывания"},{"id":"false_negative_cost","label":"Опасно пропустить целевой случай"},{"id":"regression_error","label":"Нужно оценить среднюю ошибку числового прогноза"}]},"correct_answer":{"matches":{"precision":"false_positive_cost","recall":"false_negative_cost","mae":"regression_error"}},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-M04 - Простая модель оттока","question_text":"Опишите минимальный план построения простой модели оттока клиентов по признакам tenure, monthly_spend и support_tickets.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["сформулирована целевая переменная оттока","описано разбиение train/test или validation","упомянута обработка пропусков и масштабирование при необходимости","выбрана простая модель классификации","указаны метрики качества, например ROC AUC, precision, recall"]}},
  {"competency_code":"simple_models","title":"SM-M05 - Интерпретация коэффициента","question_text":"В линейной регрессии цены жилья коэффициент при area положительный. Объясните, как корректно интерпретировать этот коэффициент и какие ограничения есть у такого вывода.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["объяснено направление связи при прочих равных","указано, что коэффициент не обязательно доказывает причинность","учтены другие признаки и возможная мультиколлинеарность","упомянута проверка качества и остатков модели"]}},
  {"competency_code":"simple_models","title":"SM-H01 - Кейс с дисбалансом классов","question_text":"Кейс. Модель выявления мошеннических операций дала accuracy 0.98. В тесте 10000 операций, мошеннических 150. Модель нашла 40 мошеннических операций, из них 30 действительно мошеннические. Объясните, почему accuracy недостаточна, и какие метрики рассчитать.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["распознан дисбаланс классов","объяснено ограничение accuracy","рассчитаны или качественно описаны precision и recall","упомянута confusion matrix","вывод связан с ценой ложноположительных и ложноотрицательных ошибок"]}},
  {"competency_code":"simple_models","title":"SM-H02 - Кейс выбора модели","question_text":"Кейс. Нужно прогнозировать цену аренды квартиры по площади, району, числу комнат и расстоянию до метро. Данных 5000 строк. Руководитель просит интерпретируемое базовое решение. Какую простую модель выбрать, какие признаки подготовить и как оценить качество?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["выбрана линейная или регуляризованная регрессия как интерпретируемый baseline","описана подготовка категориального района и числовых признаков","указано разбиение train/test или cross-validation","названы метрики MAE, RMSE или R2","объяснена интерпретация коэффициентов и ограничения модели"]}},
  {"competency_code":"simple_models","title":"SM-H03 - Кейс с кластеризацией клиентов","question_text":"Кейс. Есть клиенты с признаками purchase_frequency, avg_order_value и days_since_last_order. Целевой переменной нет, бизнес хочет выделить сегменты. Опишите подход к кластеризации и проверке полезности результата.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["распознана задача без целевой переменной","предложено масштабирование признаков","выбран простой метод кластеризации, например K-means, с подбором числа кластеров","описана интерпретация профилей кластеров","указана проверка бизнес-полезности и устойчивости сегментов"]}},
  {"competency_code":"simple_models","title":"SM-H04 - Оценка качества классификатора","question_text":"Для модели оттока какие элементы анализа качества стоит включить в отчет?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"confusion","label":"Confusion matrix"},{"id":"threshold","label":"Анализ порога классификации"},{"id":"roc_pr","label":"ROC AUC или PR AUC с учетом дисбаланса"},{"id":"train_only","label":"Только качество на обучающей выборке"}],"correct_answer":{"option_ids":["confusion","threshold","roc_pr"]},"rubric":{"criteria":[]}},
  {"competency_code":"simple_models","title":"SM-H05 - Ошибка моделирования и риск","question_text":"Сопоставьте ошибку построения модели с возможным риском.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"test_leak","label":"Данные test использованы при подборе преобразований"},{"id":"accuracy_imbalance","label":"Оценка только accuracy при сильном дисбалансе"},{"id":"no_baseline","label":"Нет простой базовой модели для сравнения"}],"matches":[{"id":"overestimate","label":"Качество может быть завышено"},{"id":"wrong_metric","label":"Можно пропустить плохое качество по редкому классу"},{"id":"no_reference","label":"Непонятно, дает ли модель выигрыш относительно простого правила"}]},"correct_answer":{"matches":{"test_leak":"overestimate","accuracy_imbalance":"wrong_metric","no_baseline":"no_reference"}},"rubric":{"criteria":[]}},

  {"competency_code":"data_visualization","title":"DV-E01 - Тренд во времени","question_text":"Какой тип графика обычно подходит для отображения динамики показателя по датам?","task_type":"single_choice","difficulty":"easy","options":[{"id":"line","label":"Линейный график"},{"id":"pie","label":"Круговая диаграмма для каждого дня"},{"id":"scatter_only","label":"Только диаграмма рассеяния"},{"id":"table_only","label":"Только текстовая таблица"}],"correct_answer":{"option_id":"line"},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-E02 - Распределение числового признака","question_text":"Какой график подходит для первичного просмотра распределения числового признака?","task_type":"single_choice","difficulty":"easy","options":[{"id":"histogram","label":"Гистограмма"},{"id":"map","label":"Карта мира"},{"id":"network","label":"Сетевой граф"},{"id":"gantt","label":"Диаграмма Ганта"}],"correct_answer":{"option_id":"histogram"},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-E03 - Подписи осей","question_text":"Что обязательно помогает корректно интерпретировать график?","task_type":"single_choice","difficulty":"easy","options":[{"id":"axis_labels","label":"Подписанные оси и единицы измерения"},{"id":"decor","label":"Максимум декоративных эффектов"},{"id":"random_colors","label":"Случайные цвета без легенды"},{"id":"hide_scale","label":"Скрытая шкала значений"}],"correct_answer":{"option_id":"axis_labels"},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-E04 - Элементы качественного графика","question_text":"Какие элементы повышают понятность аналитического графика? Выберите все подходящие варианты.","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"title","label":"Содержательный заголовок"},{"id":"units","label":"Единицы измерения и подписи осей"},{"id":"legend","label":"Легенда, если используется несколько рядов"},{"id":"3d","label":"3D-эффект без необходимости"}],"correct_answer":{"option_ids":["title","units","legend"]},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-E05 - График и задача","question_text":"Сопоставьте задачу с подходящим типом визуализации.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"trend","label":"Динамика продаж по дням"},{"id":"distribution","label":"Распределение суммы заказа"},{"id":"relationship","label":"Связь цены и площади"}],"matches":[{"id":"line","label":"Линейный график"},{"id":"hist","label":"Гистограмма или boxplot"},{"id":"scatter","label":"Диаграмма рассеяния"}]},"correct_answer":{"matches":{"trend":"line","distribution":"hist","relationship":"scatter"}},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-M01 - Выбор графика для долей","question_text":"Нужно показать долю трех каналов привлечения в общей выручке за один месяц. Какой вариант чаще всего будет понятнее для сравнения долей?","task_type":"single_choice","difficulty":"medium","options":[{"id":"bar","label":"Столбчатая диаграмма с долями или значениями"},{"id":"many_pies","label":"Много круговых диаграмм без подписей"},{"id":"line_no_time","label":"Линейный график без временной оси"},{"id":"raw_json","label":"Сырой JSON"}],"correct_answer":{"option_id":"bar"},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-M02 - Сравнение групп","question_text":"Вы сравниваете распределение времени доставки в трех регионах. Какие визуализации подойдут?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"boxplot","label":"Boxplot по регионам"},{"id":"violin","label":"Violin plot при необходимости показать форму распределения"},{"id":"hist_facets","label":"Гистограммы по регионам в одинаковой шкале"},{"id":"pie","label":"Круговая диаграмма для каждого отдельного заказа"}],"correct_answer":{"option_ids":["boxplot","violin","hist_facets"]},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-M03 - Ошибка графика и исправление","question_text":"Сопоставьте ошибку визуализации с исправлением.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"truncated_axis","label":"Ось Y обрезана и преувеличивает различия"},{"id":"too_many_colors","label":"Слишком много цветов без смысла"},{"id":"no_units","label":"Нет единиц измерения"}],"matches":[{"id":"show_scale","label":"Показать корректную шкалу или явно обозначить обрезку"},{"id":"semantic_palette","label":"Использовать ограниченную осмысленную палитру"},{"id":"add_units","label":"Добавить подписи осей и единицы"}]},"correct_answer":{"matches":{"truncated_axis":"show_scale","too_many_colors":"semantic_palette","no_units":"add_units"}},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-M04 - График для отчета продаж","question_text":"Есть продажи по дням за 6 месяцев и отметки маркетинговых кампаний. Опишите, как визуализировать динамику так, чтобы руководитель увидел тренд и влияние кампаний.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["выбран линейный график или временной ряд","предложено добавить отметки кампаний или аннотации","учтена агрегация по дням или неделям","указаны подписи осей, период и единицы измерения","описано, какой вывод должен быть виден из графика"]}},
  {"competency_code":"data_visualization","title":"DV-M05 - Визуализация выбросов","question_text":"Нужно показать, что в суммах заказов есть несколько экстремально крупных значений. Какие графики и настройки вы предложите?","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["предложены boxplot, гистограмма или scatter по времени","упомянута лог-шкала или отдельный масштаб при сильной асимметрии","описана маркировка или аннотация выбросов","объяснено, как не скрыть типичные значения"]}},
  {"competency_code":"data_visualization","title":"DV-H01 - Кейс с дашбордом конверсии","question_text":"Кейс. Воронка продукта имеет этапы: визит, регистрация, добавление товара, оплата. По каналам traffic есть разные объемы и конверсии. Нужно подготовить визуализацию для маркетинга. Какие графики выбрать и как избежать неверной интерпретации?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["предложена воронка или столбчатые диаграммы по этапам","каналы сравниваются по конверсиям и объемам отдельно","учтены абсолютные числа, чтобы не переоценить малые каналы","описаны подписи, период и сегменты","сформулирован вывод, пригодный для маркетингового решения"]}},
  {"competency_code":"data_visualization","title":"DV-H02 - Кейс с сезонностью","question_text":"Кейс. Есть ежедневная выручка за 2 года, выраженная недельная сезонность и праздничные пики. Руководителю нужно понять общий тренд без потери сезонных эффектов. Опишите визуальное решение.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["предложен временной график с агрегированием или скользящим средним","сезонность не уничтожается, а показывается дополнительным слоем или разрезом","отмечены праздники или акции","учтена шкала и подписи периода","описано, как отделить тренд от краткосрочного шума"]}},
  {"competency_code":"data_visualization","title":"DV-H03 - Кейс с визуализацией модели","question_text":"Кейс. Модель классификации оттока имеет разные precision и recall при разных порогах. Нужно объяснить бизнесу компромисс выбора порога. Какие визуализации использовать?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["предложена confusion matrix для выбранного порога","предложены precision-recall curve или график метрик по порогам","объяснен компромисс ложных срабатываний и пропусков","визуализация связана с бизнес-стоимостью ошибок","избегается вывод только по одной accuracy"]}},
  {"competency_code":"data_visualization","title":"DV-H04 - Выбор визуализаций для кейса","question_text":"У вас есть продажи по датам, регионам и категориям товаров. Нужно найти сезонность, сравнить регионы и увидеть распределение чеков. Какие визуализации выбрать?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"line_time","label":"Линейный график продаж по времени"},{"id":"bar_region","label":"Столбчатая диаграмма или small multiples для регионов"},{"id":"hist_amount","label":"Гистограмма или boxplot сумм заказов"},{"id":"pie_all_orders","label":"Круговая диаграмма из тысяч отдельных заказов"}],"correct_answer":{"option_ids":["line_time","bar_region","hist_amount"]},"rubric":{"criteria":[]}},
  {"competency_code":"data_visualization","title":"DV-H05 - Цель и визуальный прием","question_text":"Сопоставьте цель аналитика с визуальным приемом.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"highlight_change","label":"Подчеркнуть изменение после запуска акции"},{"id":"compare_distributions","label":"Сравнить распределения по сегментам"},{"id":"show_uncertainty","label":"Показать неопределенность оценки"}],"matches":[{"id":"annotation","label":"Аннотация события и вертикальная отметка на временном графике"},{"id":"box_violin","label":"Boxplot или violin plot в общей шкале"},{"id":"ci_band","label":"Доверительный интервал или полоса неопределенности"}]},"correct_answer":{"matches":{"highlight_change":"annotation","compare_distributions":"box_violin","show_uncertainty":"ci_band"}},"rubric":{"criteria":[]}},

  {"competency_code":"business_interpretation","title":"AI-E01 - Бизнес-вывод","question_text":"Что отличает бизнес-вывод от простого пересказа числа?","task_type":"single_choice","difficulty":"easy","options":[{"id":"action_context","label":"Он связывает результат анализа с контекстом и возможным решением"},{"id":"repeat_metric","label":"Он только повторяет значение метрики"},{"id":"hide_limits","label":"Он скрывает ограничения данных"},{"id":"random_opinion","label":"Он заменяет данные личным мнением"}],"correct_answer":{"option_id":"action_context"},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-E02 - Ограничения вывода","question_text":"Почему в аналитическом отчете важно указывать ограничения данных?","task_type":"single_choice","difficulty":"easy","options":[{"id":"trust","label":"Чтобы читатель понимал надежность и границы применимости вывода"},{"id":"decorate","label":"Чтобы увеличить объем текста"},{"id":"hide_error","label":"Чтобы скрыть ошибки анализа"},{"id":"replace_metric","label":"Чтобы не показывать метрики"}],"correct_answer":{"option_id":"trust"},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-E03 - Практическая значимость","question_text":"Что означает практическая значимость результата?","task_type":"single_choice","difficulty":"easy","options":[{"id":"business_value","label":"Размер эффекта достаточно важен для решения в реальном контексте"},{"id":"p_only","label":"p-value меньше 0.05 при любом размере эффекта"},{"id":"chart_beauty","label":"График выглядит красиво"},{"id":"row_count","label":"В таблице много строк"}],"correct_answer":{"option_id":"business_value"},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-E04 - Хороший аналитический вывод","question_text":"Какие элементы должен содержать хороший аналитический вывод? Выберите все подходящие варианты.","task_type":"multiple_choice","difficulty":"easy","options":[{"id":"metric","label":"Ключевой результат или метрика"},{"id":"context","label":"Контекст и сравнение с базой"},{"id":"action","label":"Возможное действие или решение"},{"id":"no_limits","label":"Полное отсутствие ограничений и оговорок"}],"correct_answer":{"option_ids":["metric","context","action"]},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-E05 - Результат и формулировка","question_text":"Сопоставьте аналитический результат с более корректной бизнес-формулировкой.","task_type":"matching","difficulty":"easy","options":{"pairs":[{"id":"conversion_up","label":"Конверсия выросла с 5% до 5.4%"},{"id":"delivery_tail","label":"5% доставок дольше недели"},{"id":"model_recall_low","label":"Recall модели риска низкий"}],"matches":[{"id":"small_effect","label":"Рост есть, но нужно оценить экономический эффект и стоимость внедрения"},{"id":"sla_issue","label":"Есть зона риска для SLA и клиентского опыта"},{"id":"miss_cases","label":"Модель пропускает часть целевых случаев, нужно оценить цену пропуска"}]},"correct_answer":{"matches":{"conversion_up":"small_effect","delivery_tail":"sla_issue","model_recall_low":"miss_cases"}},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-M01 - Интерпретация роста метрики","question_text":"Конверсия выросла с 10.0% до 10.2% на большой выборке, p-value меньше 0.05. Какой вывод наиболее корректен?","task_type":"single_choice","difficulty":"medium","options":[{"id":"check_practical","label":"Эффект статистически заметен, но нужно оценить практическую значимость и экономический смысл"},{"id":"huge_success","label":"Это гарантированно крупный бизнес-успех"},{"id":"ignore","label":"p-value меньше 0.05 всегда означает, что результат надо игнорировать"},{"id":"no_data","label":"Данных недостаточно, потому что p-value есть"}],"correct_answer":{"option_id":"check_practical"},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-M02 - Что добавить в отчет","question_text":"Модель показала ROC AUC 0.84. Какие сведения нужно добавить, чтобы бизнес мог принять решение?","task_type":"multiple_choice","difficulty":"medium","options":[{"id":"threshold_metrics","label":"Метрики при выбранном пороге: precision, recall, число срабатываний"},{"id":"error_cost","label":"Стоимость ложноположительных и ложноотрицательных ошибок"},{"id":"segment_quality","label":"Качество на важных сегментах"},{"id":"auc_only","label":"Только ROC AUC без дополнительного контекста"}],"correct_answer":{"option_ids":["threshold_metrics","error_cost","segment_quality"]},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-M03 - Метрика и бизнес-вопрос","question_text":"Сопоставьте метрику с бизнес-вопросом.","task_type":"matching","difficulty":"medium","options":{"pairs":[{"id":"conversion","label":"Конверсия"},{"id":"retention","label":"Retention"},{"id":"aov","label":"Средний чек"}],"matches":[{"id":"purchase_share","label":"Какая доля пользователей совершает целевое действие"},{"id":"return_share","label":"Какая доля клиентов возвращается после первого периода"},{"id":"order_value","label":"Сколько денег в среднем приносит заказ"}]},"correct_answer":{"matches":{"conversion":"purchase_share","retention":"return_share","aov":"order_value"}},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-M04 - Вывод по сегментам","question_text":"В отчете видно, что сегмент A дает 60% выручки, но имеет самый низкий retention. Сформулируйте бизнес-интерпретацию и дальнейшие проверки.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["связаны выручка и удержание, а не перечислены отдельно","сделан вывод о риске потери важного сегмента","предложены проверки по когорте, продукту или каналу","указаны возможные действия: удержание, коммуникации, анализ причин оттока"]}},
  {"competency_code":"business_interpretation","title":"AI-M05 - Ограничение корреляции","question_text":"Аналитик обнаружил положительную корреляцию между рекламными расходами и продажами. Объясните, почему этого недостаточно для причинного вывода и какие дополнительные проверки нужны.","task_type":"text","difficulty":"medium","options":[],"correct_answer":null,"rubric":{"criteria":["объяснено, что корреляция не доказывает причинность","упомянуты возможные смешивающие факторы, сезонность или общий тренд","предложен эксперимент, квазиэксперимент или контрольные переменные","сформулирован осторожный бизнес-вывод"]}},
  {"competency_code":"business_interpretation","title":"AI-H01 - Кейс с запуском фичи","question_text":"Кейс. После запуска новой функции недельный retention вырос с 28% до 30%, но активность выросла только у новых пользователей из платного канала. Опишите, какой бизнес-вывод можно сделать и какие ограничения нужно указать.","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["эффект интерпретирован по сегментам, а не только в среднем","указано, что общий рост может быть связан с изменением состава трафика","предложены когортный анализ или контроль канала привлечения","оценена практическая значимость роста","сформулированы осторожные рекомендации по фиче"]}},
  {"competency_code":"business_interpretation","title":"AI-H02 - Кейс с моделью риска","question_text":"Кейс. Модель риска заявок имеет precision 0.80 и recall 0.35. Проверка заявки вручную стоит дорого, но пропущенный рискованный клиент приносит большие потери. Как интерпретировать результат для бизнеса и что предложить дальше?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["объяснены precision и recall в бизнес-терминах","распознан низкий recall как риск пропуска опасных случаев","учтена стоимость ручной проверки и пропуска","предложен подбор порога или сегментный подход","сформулирована рекомендация без утверждения, что модель уже достаточна"]}},
  {"competency_code":"business_interpretation","title":"AI-H03 - Кейс с противоречивыми метриками","question_text":"Кейс. В эксперименте средний чек вырос на 8%, но конверсия снизилась на 5%, а общая выручка почти не изменилась. Как сформулировать итог для руководителя и какие дополнительные разрезы проверить?","task_type":"text","difficulty":"hard","options":[],"correct_answer":null,"rubric":{"criteria":["не делается односторонний вывод только по среднему чеку","сопоставлены средний чек, конверсия и общая выручка","предложены разрезы по сегментам, каналам, новым и старым пользователям","упомянута проверка статистической и практической значимости","сформулирована рекомендация: продолжить тест, сегментировать или не раскатывать полностью"]}},
  {"competency_code":"business_interpretation","title":"AI-H04 - Признаки зрелого вывода","question_text":"Какие признаки показывают, что аналитический вывод готов для бизнес-решения?","task_type":"multiple_choice","difficulty":"hard","options":[{"id":"effect_size","label":"Показан размер эффекта в понятных бизнес-единицах"},{"id":"uncertainty","label":"Указана неопределенность или ограничения данных"},{"id":"next_action","label":"Предложено действие или вариант решения"},{"id":"metric_only","label":"Есть только таблица метрик без интерпретации"}],"correct_answer":{"option_ids":["effect_size","uncertainty","next_action"]},"rubric":{"criteria":[]}},
  {"competency_code":"business_interpretation","title":"AI-H05 - Аналитическая ситуация и вывод","question_text":"Сопоставьте ситуацию с наиболее корректной интерпретацией.","task_type":"matching","difficulty":"hard","options":{"pairs":[{"id":"avg_up_median_flat","label":"Среднее выросло, медиана не изменилась"},{"id":"segment_effect","label":"Эффект есть только в одном малом сегменте"},{"id":"model_good_auc_bad_recall","label":"ROC AUC хороший, recall на рабочем пороге низкий"}],"matches":[{"id":"outlier_or_top","label":"Рост может быть вызван верхним хвостом, нужно проверить распределение"},{"id":"limited_rollout","label":"Нужна сегментная рекомендация, а не общий вывод на всех пользователей"},{"id":"threshold_problem","label":"Нужно пересмотреть порог и стоимость ошибок перед внедрением"}]},"correct_answer":{"matches":{"avg_up_median_flat":"outlier_or_top","segment_effect":"limited_rollout","model_good_auc_bad_recall":"threshold_problem"}},"rubric":{"criteria":[]}}
]
$task_bank$::jsonb) AS seed(
        competency_code text,
        title text,
        question_text text,
        task_type text,
        difficulty text,
        options jsonb,
        correct_answer jsonb,
        rubric jsonb
    )
),
updated AS (
    UPDATE tasks t
    SET
        competency_id = c.id,
        task_type = s.task_type,
        difficulty = s.difficulty,
        options = s.options,
        correct_answer = s.correct_answer,
        rubric = s.rubric,
        is_active = TRUE
    FROM task_seed s
    JOIN competencies c ON c.code = s.competency_code
    WHERE t.title = s.title
      AND t.question_text = s.question_text
    RETURNING t.id
)
INSERT INTO tasks (
    competency_id,
    title,
    question_text,
    task_type,
    difficulty,
    options,
    correct_answer,
    rubric,
    is_active
)
SELECT
    c.id,
    s.title,
    s.question_text,
    s.task_type,
    s.difficulty,
    s.options,
    s.correct_answer,
    s.rubric,
    TRUE
FROM task_seed s
JOIN competencies c ON c.code = s.competency_code
WHERE NOT EXISTS (
    SELECT 1
    FROM tasks t
    WHERE t.title = s.title
      AND t.question_text = s.question_text
);

DELETE FROM tasks t
WHERE t.is_active = FALSE
  AND NOT EXISTS (
      SELECT 1
      FROM answers a
      WHERE a.task_id = t.id
  );

COMMIT;
